/*
 Copyright (c) 2013, Raonwiz Technology Inc. All rights reserved.
*/
if(!window.DEXT5){window.DEXT5=function(){var a=window.DEXT5_ROOTPATH||"";if(!a)for(var c=document.getElementsByTagName("script"),b=0;b<c.length;b++){var d=c[b].src.match(/(^|.*[\\\/])dext5editor.js(?:\?.*)?$/i);if(d){a=d[1];break}}-1==a.indexOf(":/")&&(a=0===a.indexOf("/")?location.href.match(/^.*?:\/\/[^\/]*/)[0]+a:location.href.match(/^[^\?]*\/(?:)/)[0]+a);a=a.split("/js")[0]+"/";if(!a)throw"DEXT5 installation path could not be automatically detected.";return{isRelease:!0,cabVersion:"1,0,0,28",
version:"DEXT5 Editor",ReleaseVer:"917105.1126",rootPath:a,DEXTMULTIPLE:{}}}();DEXT5.brower||(DEXT5.browser=function(){var a=navigator.userAgent.toLowerCase(),c=window.opera,c={ie:-1<a.search("msie")?!0:!1,opera:!!c&&c.version,webkit:-1<a.indexOf(" applewebkit/"),mac:-1<a.indexOf("macintosh"),quirks:"BackCompat"==document.compatMode,mobile:-1<a.indexOf("mobile"),iOS:/(ipad|iphone|ipod)/.test(a),isCustomDomain:function(){if(!this.ie)return!1;var a=document.domain,b=window.location.hostname;return a!=
b&&a!="["+b+"]"},isHttps:"https:"==location.protocol};c.gecko="Gecko"==navigator.product&&!c.webkit&&!c.opera;c.webkit&&(-1<a.indexOf("chrome")?(c.chrome=!0,-1<a.indexOf("opr")&&(c.opera=!0,c.chrome=!1)):c.safari=!0);var b;c.ie&&(b=c.quirks||!document.documentMode?parseFloat(a.match(/msie (\d+)/)[1]):document.documentMode,c.ie9=9==b,c.ie8=8==b,c.ie7=7==b,c.ie6=7>b||c.quirks);c.gecko&&(b=a.match(/rv:([\d\.]+)/))&&(b=b[1].split("."),b=1E4*b[0]+100*(b[1]||0)+1*(b[2]||0));c.webkit&&(b=parseFloat(a.match(/ applewebkit\/(\d+)/)[1]));
return c}());var DEXTWIN=window,DEXTDOC=document;top!=window&&(DEXTWIN="undefined"!=typeof window.frameElement.contentWindow?window.frameElement.contentWindow:"undefined"!=typeof window.frameElement.contentDocument?window.frameElement.contentDocument.defaultView:top,DEXTDOC="undefined"!=typeof window.frameElement.contentDocument?window.frameElement.contentDocument:"undefined"!=typeof window.frameElement.contentWindow?window.frameElement.contentWindow.document:top.document);top.DEXTWIN=DEXTWIN;top.DEXTDOC=
DEXTDOC;top.G_SELECTED_ELEMENT=null;top.G_CURREDITOR=null;top.DEXT5=DEXT5}DEXT5.config={Width:"",Height:"",SkinName:"",InitXml:"",ToSavePathURL:"",InitVisible:!0,zTopMenu:"",zToolBar:"",zStatusBar:"",DefaultMessage:"",FirstLoadType:"",FirstLoadMessage:""};
DEXT5.ajax=function(){var a=function(){if(!DEXT5.browser.ie||"file:"!=location.protocol){try{return new XMLHttpRequest}catch(a){}try{return new ActiveXObject("Msxml2.XHLHTTP")}catch(b){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(c){}}return null},c=function(a){return 4==a.readyState&&(200<=a.status&&300>a.status||304==a.status||0===a.status||1223==a.status)},b=function(a){return c(a)?a.responseText:null},d=function(a){if(c(a)){var b=a.responseXML;return b?b:a.responseText}return null},
f=function(b,c,d){var f=!!c,l=a();if(!l)return null;l.open("GET",b,f);f&&(l.onreadystatechange=function(){4==l.readyState&&(c(d(l)),l=null)});try{l.send(null)}catch(q){return null}setTimeout(function(){l.abort()},5E3);return f?"":d(l)};return{load:function(a,c){return f(a,c,b)},loadXml:function(a,b){return f(a,b,d)}}}();
DEXT5.util={trim:function(a){return a.trim?a.trim():a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},setClass:function(a,c){a.className=c},getClass:function(a){return a.className},checkUrl:function(a){var c=!1;return c=RegExp(/(http|ftp|https|news):\/\/[\w-]+(\.[\w-]+)+([\w.,@?^=%&amp;:\/~+#-]*[\w@?^=%&amp;\/~+#-])?/).test(a)},makeIframe:function(){var a;try{a=top.DEXTDOC.createElement('<iframe frameborder="0" >')}catch(c){a=top.DEXTDOC.createElement("iframe")}a.style.margin="0px";a.style.padding="0px";a.frameBorder=
0;a.style.overflow="auto";a.style.overflowX="hidden";a.style.backgroundColor="#ffffff";return a},ieInnerHTML:function(a,c){var b=a.innerHTML?String(a.innerHTML):a,d=b.match(/(<.+[^>])/g);if(d)for(var f=0;f<d.length;f++){var e,g=d[f];if(e=d[f].match(/\=[a-zA-Z\.\:\[\]_\(\)\&\$\%#\@\!0-9\/]+[?\s+|?>]/g))for(var h=0,p=e.length;h<p;)d[f]=d[f].replace(e[h],e[h].replace(/(\=)([a-zA-Z\.\:\[\]_\(\)\&\$\%#\@\!0-9\/]+)?([\s+|?>])/g,function(){var a=Array.prototype.slice.call(arguments);return'="'+(c?a[2].toLowerCase():
a[2])+'"'+a[3]})),h+=1;b=b.replace(g,d[f])}return b},addEvent:function(a,c,b,d){a.addEventListener?a.addEventListener(c,b,d):a.attachEvent&&a.attachEvent("on"+c,b)},removeEvent:function(a,c,b,d){a.removeEventListener?a.removeEventListener(c,b,d):a.detachEvent&&a.detachEvent("on"+c,b)},stopEvent:function(a){"bubbles"in a?a.bubbles&&a.stopPropagation():a.cancelBubble=!0},cancelEvent:function(a){a.preventDefault?a.preventDefault():a.returnValue=!1},ajax:{xml_http_request:function(){var a;window.ActiveXObject?
a=new ActiveXObject("Microsoft.XMLHTTP"):window.XMLHttpRequest&&(a=new XMLHttpRequest);return a}},url:{full_url:function(a){var c="";if(0==a.indexOf("http://")||0==a.indexOf("https://"))c=a;else if(0==a.indexOf("/"))c=location.protocol+"//"+location.host+a;else var c=location.href,b=c.lastIndexOf("/"),c=c.substring(0,b+1),c=c+a;return c}},xml:{count:function(a,c){return a?a.getElementsByTagName(c).length:0},getNode:function(a,c){return this.getNodeIdx(a,c,0)},getNodeIdx:function(a,c,b){return a.getElementsByTagName(c)[b]},
getNodeValue:function(a,c){return this.getNodeValueIdx(a,c,0)},getNodeValueIdx:function(a,c,b){a=this.getNodeIdx(a,c,b);return this.getValue(a)},getValue:function(a){var c="";if(void 0!=a)try{0<a.childNodes.length&&(c=a.firstChild.nodeValue)}catch(b){c="parsing error"}return c}},htmlToLowerCase:function(a){var c=RegExp("<[^>]+>","g");results=a.match(c);for(i=0;i<results.length;i++){original=results[i];stripquoted=results[i].replace(/ [^=]+= *"[^"]*"/g,"");if(-1==stripquoted.indexOf("background-image:")&&
(c=RegExp(" [^=]+=[^ |>]+","g"),unquoted=stripquoted.match(c)))for(j=0;j<unquoted.length;j++)addquotes=unquoted[j].replace(/( [^=]+=)([^ |>]+)/g,'$1"$2"'),results[i]=results[i].replace(unquoted[j],addquotes);results[i]=results[i].replace(/<\/?[^>|^ ]+/,function(a){return a.toLowerCase()});results[i]=results[i].replace(/ [^=]+="/g,function(a){return a.toLowerCase()});a=a.replace(original,results[i])}return a},hexDigits:"0123456789abcdef".split(""),hex:function(a){return isNaN(a)?"00":this.hexDigits[(a-
a%16)/16]+this.hexDigits[a%16]},rgb2hex:function(a){a=a.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/);if(!(null==a||4>a.length))return"#"+this.hex(a[1])+this.hex(a[2])+this.hex(a[3])},dextSetAttribute:function(a,c,b,d){"string"==typeof b?0<b.length&&(a.style[c]=b+d):"number"==typeof b&&(a.style[c]=b)},getRealBackgoundImagePath:function(a){return a=a.replace(/url\(\s*(["']?)\s*([^\)]*)\s*\1\s*\)/i,function(a,b,d){return d})},replaceTagName:function(a,c){for(var b=c.split(","),d=0;d<b.length;d++){var f=
RegExp("<\\/"+b[d]+">","gi"),e=a.match(RegExp("<"+b[d]+"[^>]*>","gi")),g="";if(e)for(var h=0;h<e.length;h++)g=e[h],g=g.replace("<","&lt;"),g=g.replace(">","&gt;"),a=a.replace(e[h],g);a=a.replace(f,"&lt;/"+b[d]+"&gt;")}return a},removeTags:function(a,c){for(var b=c.split(","),d=null,f=0;f<b.length;f++)for(var d=a.getElementsByTagName(b[f]),e=0;e<d.length;e++)this.RemoveElement(d[e])},removeAttributes:function(a,c,b){a=c.split(",");for(c=0;c<b.length;c++)for(var d=0;d<a.length;d++)b[c].removeAttribute(a[d])},
RemoveElement:function(a){for(;a.firstChild;)a.parentNode.insertBefore(a.firstChild,a);a.parentNode.removeChild(a)},officeClean:function(a,c){var b=null,d=[],b=RegExp("([-]{0,1}[0-9]+|[-]{0,1}[0-9]*[.]{1}[0-9]+)pt","gi");a=a.replace(b,function(a,b){var c=4*b/3;0<c&&1>c&&(c=1);return Math.round(c)+"px"});b=RegExp("([-]{0,1}[0-9]+|[-]{0,1}[0-9]*[.]{1}[0-9]+)cm","gi");a=a.replace(b,function(a,b){var c=37.795275593333*b;0<c&&1>c&&(c=1);return Math.round(c)+"px"});a=a.replace(/\.0px/g,"px");a=a.replace(/\t/g,
"");a=a.replace(/<o:p>/gi,"");a=a.replace(/<\/o:p>/gi,"");a=a.replace(/lang=[\"]?en-us[\"]?/gi,"");a=a.replace(/class=[\"]?(mso)\w+[\"]?/gi,"");b=RegExp('mso-[^:]+:[^;">]+;',"gi");a=a.replace(b,"");b=RegExp('mso-[^:]+:[^;">]+("|\')',"gi");a=a.replace(b,"$1");for(var f=0;5>f;f++){for(var d=["o:p","span","font"],e=0;e<d.length;e++)b=RegExp("<"+d[e]+"[^>]*></"+d[e]+">","gi"),a=a.replace(b,""),b=RegExp("<"+d[e]+"[^>]*>&nbsp;</"+d[e]+">","gi"),a=a.replace(b,"&nbsp;");d=["font"];for(e=0;e<d.length;e++)b=
RegExp("<"+d[e]+"[^>]*>([^<]+)</"+d[e]+">","gi"),a=a.replace(b,"$1");d=["o","v","w","m","x"];for(e=0;e<d.length;e++)b=RegExp("<"+d[e]+":[^/>]+/>","gi"),a=a.replace(b,""),b=RegExp("<"+d[e]+":[^>]+>[^<]*</"+d[e]+":[^>]+>","gi"),a=a.replace(b,"")}a=a.replace(/style=""/gi,"");a=a.replace(/style=''/gi,"");a=a.replace(/\s>/gi,">");!1==c&&(a=a.replace(/file:\/\/\//gi,"dext_local_file_image"),b=RegExp("<img[^>]+dext_local_file_image[^>]+>","gi"),a=a.replace(b,""));return a}};
function DEXT_CONFIG(){this.dext_path="";this.lang="ko";this.defaultLineHeight=this.defaultFontFamily=this.defaultFontSize="";this.status_bar=this.tool_bar=this.top_memu=this.accessibility="0";this.toSavePathURL="dext5data";this.saveFolderNameRule="YYYY/MM";this.saveFileNameRule="GUID";this.showDialogPosition="0";this.productKey=this.image_convert_height=this.image_convert_width=this.image_convert_format="";this.mimeUse=this.plugInUse="0";this.firstLoadMessage=this.firstLoadType=this.defaultMessage=
"";this.style={skinName:"blue",width:"100%",height:"600px",InitVisible:!0,isFontSizeUse:!0};this.webPath={image:DEXT5.rootPath+"images/dext/",page:DEXT5.rootPath+"pages/",js:DEXT5.rootPath+"js/",css:DEXT5.rootPath+"css/",include:DEXT5.rootPath+"include/",config:DEXT5.rootPath+"config/"};this.holderID="";this.config_url=DEXT5.rootPath+"config/dext_editor.xml";this.emoticon_url=DEXT5.rootPath+"config/dext_emoticon.xml";this.forms_url=DEXT5.rootPath+"config/dext_formlist.xml";this.post_url=DEXT5.rootPath+
"handler/upload_handler.ashx";this.proxy_url="";this.plugin_root=DEXT5.rootPath+"plugin/";this.plugin_version=DEXT5.cabVersion;this.editor_url=DEXT5.isRelease?DEXT5.rootPath+"pages/dextRelease.html":DEXT5.rootPath+"pages/dext.html";this.pages={find:"dext_find.html",replace:"dext_replace.html",image:"dext_image.html",horizontal_line:"dext_horizontal_line.html",bg_image:"dext_bg_image.html",doc_bg_img:"dext_doc_bg_img.html",flash:"dext_flash.html",media:"dext_media.html",table:"dext_table.html",table_property:"dext_table_property.html",
cell_property:"dext_cell_property.html",insert_row_column:"dext_insert_row_column.html",row_property:"dext_row_property.html",column_property:"dext_column_property.html",emoticon:"dext_emoticon.html",bookmark:"dext_bookmark.html",iframe:"dext_iframe.html",hyperlink:"dext_hyperlink.html",split_cell:"dext_split_cell.html",about:"dext_about.html",symbol:"dext_symbol.html",setting:"dext_setting.html",template:"dext_template.html",tool_replace:"dext_tool_replace.html",insert_link_media:"dext_insert_link_media.html",
m_image:"dext_m_image.html",m_emoticon:"dext_m_emoticon.html",cell_border:"dext_cell_border.html"};this.editor_id=this.remove_attributes=this.remove_tags=this.replace_tagname=""}function isExistEditorName(a){if(void 0==a||""==a)return 1;a=top.DEXT5.DEXTMULTIPLE["dext_frame_"+a];return void 0==a||null==a?0:2}
function Dext5editor(a){var c=isExistEditorName(a);if(1==c)alert("DEXT5 editor's name is empty. Please, check editor's name");else if(2==c)alert("DEXT5 editor's name is already exist. Please, check editor's name");else{var b=new DEXT_CONFIG;0<DEXT5.config.InitXml.length&&(b.config_url=DEXT5.rootPath+"config/"+DEXT5.config.InitXml);c=DEXT5.ajax.loadXml(b.config_url);if(null==c)alert("ErrCode : 1000");else{top.DEXT5.DEXTMULTIPLE["dext_frame_"+a]=a;var d=DEXT5.util.xml.getNode(c,"work_config"),f=DEXT5.util.xml.getNodeValue(d,
"replace_tagname"),e=DEXT5.util.xml.getNodeValue(d,"remove_tags"),d=DEXT5.util.xml.getNodeValue(d,"remove_attributes");b.replace_tagname=f.toLowerCase();b.remove_tags=e.toLowerCase();b.remove_attributes=d.toLowerCase();var d=DEXT5.util.xml.getNode(c,"setting"),g=DEXT5.util.xml.getNodeValue(d,"width"),h=DEXT5.util.xml.getNodeValue(d,"height"),p=DEXT5.util.xml.getNodeValue(d,"skinname"),l=DEXT5.util.xml.getNodeValue(d,"lang"),q=DEXT5.util.xml.getNodeValue(d,"accessibility"),t=DEXT5.util.xml.getNodeValue(d,
"showdialog_pos"),m=DEXT5.util.xml.getNode(c,"uploader_setting"),f=DEXT5.util.xml.getNodeValue(m,"develop_langage"),e=DEXT5.util.xml.getNodeValue(m,"handler_url"),s=DEXT5.util.xml.getNodeValue(m,"to_save_path_url"),n=DEXT5.util.xml.getNodeValue(m,"save_foldername_rule"),r=DEXT5.util.xml.getNodeValue(m,"save_filename_rule"),u=DEXT5.util.xml.getNodeValue(m,"image_convert_format"),v=DEXT5.util.xml.getNodeValue(m,"image_convert_width"),m=DEXT5.util.xml.getNodeValue(m,"image_convert_height");b.image_convert_format=
u;b.image_convert_width=v;b.image_convert_height=m;b.style.width=""==DEXT5.config.Width?0==g.length?b.style.width:g:DEXT5.config.Width;b.style.height=""==DEXT5.config.Height?0==h.length?b.style.height:h:DEXT5.config.Height;b.style.skinName=""==DEXT5.config.SkinName?0==p.length?b.style.skinName:p:DEXT5.config.SkinName;b.defaultMessage=""==DEXT5.config.DefaultMessage?"":DEXT5.config.DefaultMessage;b.firstLoadType=""==DEXT5.config.FirstLoadType?"":DEXT5.config.FirstLoadType;b.firstLoadMessage=""==DEXT5.config.FirstLoadMessage?
"":DEXT5.config.FirstLoadMessage;b.toSavePathURL=""==DEXT5.config.ToSavePathURL?0==s.length?b.toSavePathURL:s:DEXT5.config.ToSavePathURL;"1"==t&&(b.showDialogPosition="1");b.lang=0==l.length?"ko":l;b.accessibility=0==q.length?"0":q;if("YYYY/"==n||"YYYY/MM/"==n||"YYYY/MM/DD/"==n||"/"==n)b.saveFolderNameRule=n;if("GUID"==r||"DATETIME"==r)b.saveFileNameRule=r;g=DEXT5.util.xml.getNodeValue(d,"topmenu");h=DEXT5.util.xml.getNodeValue(d,"toolbar");d=DEXT5.util.xml.getNodeValue(d,"statusbar");b.top_memu=
"1"==g?g:"0";b.tool_bar="1"==h||"2"==h||"3"==h?h:"0";b.status_bar="1"==d?d:"0";""!=DEXT5.config.zTopMenu&&(b.top_memu=DEXT5.config.zTopMenu);""!=DEXT5.config.zToolBar&&(b.tool_bar=DEXT5.config.zToolBar);""!=DEXT5.config.zStatusBar&&(b.status_bar=DEXT5.config.zStatusBar);d="";d=0==e.length?DEXT5.rootPath:"/"==e.substring(0,1)?location.protocol+"//"+location.host:4<e.length&&"http"==e.substring(0,4).toLowerCase()?"":DEXT5.rootPath;b.style.InitVisible=DEXT5.config.InitVisible;if(0==e.length)switch(f.toUpperCase()){case "JSP":b.post_url=
d+"handler/upload_handler.jsp";break;case "PHP":b.post_url=d+"handler/upload_handler.php";break;default:b.post_url=d+"handler/upload_handler.ashx"}else{if(4<e.length&&"http"==e.substring(0,4).toLowerCase()&&e.match(/:\/\/(.[^\/]+)/)[1]!=window.location.host){g="";switch(f.toUpperCase()){case "JSP":g=DEXT5.rootPath+"handler/upload_handler.jsp";break;case "PHP":g=DEXT5.rootPath+"handler/upload_handler.php";break;default:g=DEXT5.rootPath+"handler/upload_handler.ashx"}b.proxy_url=g}b.post_url=d+e}g=DEXT5.util.xml.getNode(c,
"license");c=DEXT5.util.xml.getNodeValue(g,"product_key");f=DEXT5.util.xml.getNodeValue(g,"license_plugin");e=DEXT5.util.xml.getNodeValue(g,"plugin_use");d=DEXT5.util.xml.getNodeValue(g,"plugin_version");g=DEXT5.util.xml.getNodeValue(g,"mime_use");b.productKey=c;""!=f&&(b.plugin_root=f);b.mimeUse="1"==g?"1":"0";b.plugInUse="1"==e?"1":"0";null!=d&&7<=d.length&&(b.plugin_version=d);if("0"==b.plugInUse&&""==b.proxy_url&&(c=DEXT5.ajax.load(b.post_url+"?dext=test"),null==c||""==c)){c="";"ko"==b.lang?(c=
"DEXT5 Editor\uc758 \uc124\uc815\uac12\uc774 \uc62c\ubc14\ub974\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4. \uc544\ub798 URL \uc811\uadfc\uc774 \uc720\ud6a8\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.\n\n"+(b.post_url+"\n\n"),c+="dext_editor.xml \ud30c\uc77c\uc758 uploader_setting \uc138\uc158\uc758 <develop_langage>\uc640 <handler_url> \uc124\uc815\uac12\uc744 \ud655\uc778\ud558\uc138\uc694."):(c="DEXT5 Editor's setting is not correct. Access the following URL is not valid.\n\n\n"+(b.post_url+"\n\n"),c+='Please check the settings, <handler_url> and <develop_langage> in "uploader_setting" session in the "dext_editor.xml.');
alert(c);return}this.editor=null;b.editor_id=a;this.FrameID="dext_frame_"+a;b.holderID="dext_frame_holder"+a;c="";if(!1==b.style.InitVisible)c='<div id="'+b.holderID+'" style="width:1px; height:1px; "></div>';else{c='<div id="'+b.holderID+'" style="width:'+b.style.width+"; height:"+b.style.height+"; ";if(DEXT5.browser.iOS||DEXT5.browser.mobile)c+=" overflow:scroll; overflow-x:hidden; -webkit-overflow-scrolling:touch; ";c+='"></div>'}document.write(c);var c=document.getElementById(b.holderID),k;try{k=
document.createElement("<iframe frameborder='0' scrolling='no'>")}catch(x){k=document.createElement("iframe"),k.setAttribute("frameborder","0"),k.setAttribute("scrolling","no")}k.setAttribute("id",this.FrameID);k.style.width="100%";k.style.height="100%";if(DEXT5.browser.iOS||DEXT5.browser.mobile)k.style.overflow="hidden",k.style.display="inline-block";k.width="100%";k.height="100%";c.appendChild(k);var w=this,c=function(){try{k.contentWindow.dext_frame_loaded_event(a,b,w);var c=window.document,c=
window.frameElement&&"undefined"!=typeof window.frameElement.contentDocument?window.frameElement.contentDocument:window.frameElement&&"undefined"!=typeof window.frameElement.contentWindow?window.frameElement.contentWindow.document:window.document,d=c.getElementsByTagName("head")[0],e=c.createElement("link");e.type="text/css";e.rel="stylesheet";e.href=b.webPath.css+"dext_editor_popup.css";d.appendChild(e)}catch(f){alert("ErrCode : 1001")}};k.addEventListener?k.addEventListener("load",c,!1):k.attachEvent&&
k.attachEvent("onload",c);k.src=b.editor_url}}};
