function onlyNumber(d){window.netscape?34<d.which&&41>d.which||(47<d.which&&58>d.which||95<d.which&&106>d.which||8==d.which||9==d.which||13==d.which||46==d.which)||(d.preventDefault?d.preventDefault():d.returnValue=!1):34<d.keyCode&&41>d.keyCode||(47<d.keyCode&&58>d.keyCode||95<d.keyCode&&106>d.keyCode||8==d.keyCode||9==d.keyCode||13==d.keyCode||46==d.keyCode)||(d.preventDefault?d.preventDefault():d.returnValue=!1)}function GetNode(d,g){return GetNodeIdx(d,g,0)}
function GetNodeIdx(d,g,f){return d.getElementsByTagName(g)[f]}function GetNodeValue(d,g){return GetNodeValueIdx(d,g,0)}function GetNodeValueIdx(d,g,f){d=GetNodeIdx(d,g,f);return GetValue(d)}function GetValue(d){var g="";try{0<d.childNodes.length&&(g=d.firstChild.nodeValue)}catch(f){g="error"}return g}function SetDivinnerHTML(d,g){try{document.getElementById(d).innerHTML=g}catch(f){}}function SetDivouterHTML(d,g){try{document.getElementById(d).outerHTML=g}catch(f){}}
function SetDivText(d,g){try{document.getElementById(d).innertText=g}catch(f){}}
function xmlhttpPostXML(d,g,f,a){var c=!1;window.ActiveXObject?c=new ActiveXObject("Microsoft.XMLHTTP"):window.XMLHttpRequest&&(c=new XMLHttpRequest,c.overrideMimeType("text/xml"));c.open("GET",d,!0);c.setRequestHeader("Content-Type","application/x-www-form-urlencoded");c.onreadystatechange=function(){4==c.readyState&&eval(f)(c.responseXML,a)};c.send();if(4==c.readyState)switch(strResponse=c.responseXML,c.status){case 404:alert("Error: Not Found. The requested URL "+d+" could not be found.");break;
case 500:handleErrFullPage(strResponse);break;default:-1<strResponse.indexOf("Error:")||-1<strResponse.indexOf("Debug:")?alert(strResponse):eval(f+"(strResponse);")}}
function xmlAdmin(d,g){var f=document.getElementById("xml_value"),a,c,h=GetNode(d,"dext5");if("1"==g){var e=GetNode(h,"license"),b=GetNodeValue(e,"product_key");a=document.createElement("input");a.setAttribute("type","hidden");a.setAttribute("id","product_key");a.setAttribute("name","product_key");a.setAttribute("value",b);f.appendChild(a);""!=b&&(a=b.split("-"),document.getElementById("product_key_1").value=a[0],document.getElementById("product_key_2").value=a[1],document.getElementById("product_key_3").value=
a[2],document.getElementById("product_key_4").value=a[3]);b=GetNodeValue(e,"license_key");document.getElementById("license_key").value=b;c=GetNodeValue(e,"license_plugin");"error"==c?document.getElementById("license_plugin").value="":document.getElementById("license_plugin").value=c;for(var k=GetNodeValue(e,"plugin_use"),b=0;b<dext5_admin_lang.plugin_use_value.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.plugin_use_value[b]),a.innerHTML=dext5_admin_lang.plugin_use_text[b],
document.getElementById("plugin_use").appendChild(a),dext5_admin_lang.plugin_use_value[b]==k&&(a.selected=!0);"1"==document.getElementById("plugin_use").value&&(document.getElementById("tr_plugin_url").style.display="",document.getElementById("tr_plugin_version").style.display="",""!=c?(document.getElementById("chk_license_plugin").checked=!1,document.getElementById("license_plugin").disabled=!1,document.getElementById("span_desc").innerHTML=dext5_admin_lang.license_url_desc2):(document.getElementById("license_plugin").disabled=
"disabled",document.getElementById("span_desc").innerHTML=dext5_admin_lang.license_url_desc1));b=GetNodeValue(e,"plugin_version");a=document.createElement("input");a.setAttribute("type","hidden");a.setAttribute("id","plugin_version");a.setAttribute("name","plugin_version");a.setAttribute("value",b);f.appendChild(a);"error"==b&&(b="");""!=b&&(a=b.split("."),document.getElementById("plugin_version1").value=a[0],document.getElementById("plugin_version2").value=a[1],document.getElementById("plugin_version3").value=
a[2],document.getElementById("plugin_version4").value=a[3])}else e=GetNode(h,"license"),b=GetNodeValue(e,"product_key"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","product_key"),a.setAttribute("name","product_key"),a.setAttribute("value",b),f.appendChild(a),b=GetNodeValue(e,"license_key"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","license_key"),a.setAttribute("name","license_key"),a.setAttribute("value",b),f.appendChild(a),
c=GetNodeValue(e,"license_plugin"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","license_plugin"),a.setAttribute("name","license_plugin"),"error"==c?a.setAttribute("value",""):a.setAttribute("value",c),f.appendChild(a),k=GetNodeValue(e,"plugin_use"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","plugin_use"),a.setAttribute("name","plugin_use"),"error"==k?a.setAttribute("value","0"):a.setAttribute("value",k),f.appendChild(a);
b=GetNode(h,"work_config");e=GetNodeValue(b,"office_clean");a=document.createElement("input");a.setAttribute("type","hidden");a.setAttribute("id","office_clean");a.setAttribute("name","office_clean");a.setAttribute("value",e);f.appendChild(a);e=GetNodeValue(b,"remove_tags");a=document.createElement("input");a.setAttribute("type","hidden");a.setAttribute("id","remove_tags");a.setAttribute("name","remove_tags");a.setAttribute("value",e);f.appendChild(a);b=GetNodeValue(b,"help_url");a=document.createElement("input");
a.setAttribute("type","hidden");a.setAttribute("id","help_url");a.setAttribute("name","help_url");a.setAttribute("value",b);f.appendChild(a);if("2"==g){e=GetNode(h,"top_menu");c=e.getElementsByTagName("menu").length;for(b=0;b<c;b++)k=GetNodeValueIdx(e,"menu",b),a=document.createElement("option"),a.setAttribute("value",k),a.innerHTML=eval("dext5_admin_lang.top_menu."+k),document.getElementById("set_menu").appendChild(a),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id",
"top_menu_pre"),a.setAttribute("name","top_menu_pre"),a.setAttribute("value",k),f.appendChild(a);for(b=0;b<dext5_admin_lang.top_menu_value.length;b++){a=!1;for(e=0;e<document.getElementById("set_menu").length;e++)if(dext5_admin_lang.top_menu_value[b]==document.getElementById("set_menu").options[e].value){a=!0;break}a||(a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.top_menu_value[b]),a.innerHTML=dext5_admin_lang.top_menu_text[b],document.getElementById("all_menu").appendChild(a))}}else for(e=
GetNode(h,"top_menu"),c=e.getElementsByTagName("menu").length,b=0;b<c;b++)k=GetNodeValueIdx(e,"menu",b),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","top_menu"),a.setAttribute("name","top_menu[]"),a.setAttribute("value",k),f.appendChild(a);if("3"==g){k=GetNode(h,"tool_bar_1");c=k.getElementsByTagName("tool").length;for(b=0;b<c;b++)e=GetNodeValueIdx(k,"tool",b),a=document.createElement("option"),a.setAttribute("value",e),a.innerHTML=eval("dext5_admin_lang.tool_bar."+
e),document.getElementById("set_menu1").appendChild(a),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","tool_bar_1_pre"),a.setAttribute("name","tool_bar_1_pre"),a.setAttribute("value",e),f.appendChild(a);k=GetNode(h,"tool_bar_2");c=k.getElementsByTagName("tool").length;for(b=0;b<c;b++)e=GetNodeValueIdx(k,"tool",b),a=document.createElement("option"),a.setAttribute("value",e),a.innerHTML=eval("dext5_admin_lang.tool_bar."+e),document.getElementById("set_menu2").appendChild(a),
a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","tool_bar_2_pre"),a.setAttribute("name","tool_bar_2_pre"),a.setAttribute("value",e),f.appendChild(a);for(b=0;b<dext5_admin_lang.tool_bar_value.length;b++){a=!1;for(e=0;e<document.getElementById("set_menu1").length;e++)if(dext5_admin_lang.tool_bar_value[b]==document.getElementById("set_menu1").options[e].value){a="separator"==document.getElementById("set_menu1").options[e].value?!1:!0;break}for(e=0;e<document.getElementById("set_menu2").length;e++)if(dext5_admin_lang.tool_bar_value[b]==
document.getElementById("set_menu2").options[e].value){a="separator"==document.getElementById("set_menu2").options[e].value?!1:!0;break}a||(a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.tool_bar_value[b]),a.innerHTML=dext5_admin_lang.tool_bar_text[b],document.getElementById("all_menu").appendChild(a))}}else{k=GetNode(h,"tool_bar_1");c=k.getElementsByTagName("tool").length;for(b=0;b<c;b++)e=GetNodeValueIdx(k,"tool",b),a=document.createElement("input"),a.setAttribute("type",
"hidden"),a.setAttribute("id","tool_bar_1"),a.setAttribute("name","tool_bar_1[]"),a.setAttribute("value",e),f.appendChild(a);k=GetNode(h,"tool_bar_2");c=k.getElementsByTagName("tool").length;for(b=0;b<c;b++)e=GetNodeValueIdx(k,"tool",b),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","tool_bar_2"),a.setAttribute("name","tool_bar_2[]"),a.setAttribute("value",e),f.appendChild(a)}if("4"==g){k=GetNode(h,"status_bar");c=k.getElementsByTagName("status").length;for(b=
0;b<c;b++)e=GetNodeValueIdx(k,"status",b),a=document.createElement("option"),a.setAttribute("value",e),a.innerHTML=eval("dext5_admin_lang.status_bar."+e),document.getElementById("set_menu").appendChild(a),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","status_bar_pre"),a.setAttribute("name","status_bar_pre"),a.setAttribute("value",e),f.appendChild(a);for(b=0;b<dext5_admin_lang.status_bar_value.length;b++){a=!1;for(e=0;e<document.getElementById("set_menu").length;e++)if(dext5_admin_lang.status_bar_value[b]==
document.getElementById("set_menu").options[e].value){a=!0;break}a||(a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.status_bar_value[b]),a.innerHTML=dext5_admin_lang.status_bar_text[b],document.getElementById("all_menu").appendChild(a))}}else for(k=GetNode(h,"status_bar"),c=k.getElementsByTagName("status").length,b=0;b<c;b++)e=GetNodeValueIdx(k,"status",b),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","status_bar"),a.setAttribute("name",
"status_bar[]"),a.setAttribute("value",e),f.appendChild(a);if("5"==g){k=GetNode(h,"remove_item");c=k.getElementsByTagName("item").length;for(b=0;b<c;b++)e=GetNodeValueIdx(k,"item",b),a=document.createElement("option"),a.setAttribute("value",e),a.innerHTML=eval("dext5_admin_lang.remove_item."+e),document.getElementById("set_menu").appendChild(a);for(b=0;b<dext5_admin_lang.remove_item_value.length;b++){a=!1;for(e=0;e<document.getElementById("set_menu").length;e++)if(dext5_admin_lang.remove_item_value[b]==
document.getElementById("set_menu").options[e].value){a=!0;break}a||(a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.remove_item_value[b]),a.innerHTML=dext5_admin_lang.remove_item_text[b],document.getElementById("all_menu").appendChild(a))}}else for(k=GetNode(h,"remove_item"),c=k.getElementsByTagName("item").length,b=0;b<c;b++)e=GetNodeValueIdx(k,"item",b),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","remove_item"),a.setAttribute("name",
"remove_item[]"),a.setAttribute("value",e),f.appendChild(a);if("6"==g)for(k=GetNode(h,"font_size"),c=k.getElementsByTagName("size").length,b=0;b<c;b++){var l=GetNodeValueIdx(k,"size",b);a=document.createElement("option");a.setAttribute("value",l);a.innerHTML=l;document.getElementById("set_font_size").appendChild(a)}else for(k=GetNode(h,"font_size"),c=k.getElementsByTagName("size").length,b=0;b<c;b++)l=GetNodeValueIdx(k,"size",b),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id",
"font_size"),a.setAttribute("name","font_size[]"),a.setAttribute("value",l),f.appendChild(a);if("7"==g){k=GetNode(h,"font_family");c=k.getElementsByTagName("font").length;for(b=0;b<c;b++)l=GetNodeValueIdx(k,"font",b),a=document.createElement("option"),a.setAttribute("value",l),a.innerHTML=l,document.getElementById("set_font_family").appendChild(a);for(b=0;b<dext5_admin_lang.font_family.length;b++){a=!1;for(e=0;e<document.getElementById("set_font_family").length;e++)if(dext5_admin_lang.font_family[b]==
document.getElementById("set_font_family").options[e].value){a=!0;break}a||(a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.font_family[b]),a.innerHTML=dext5_admin_lang.font_family[b],document.getElementById("all_font_family").appendChild(a))}}else for(k=GetNode(h,"font_family"),c=k.getElementsByTagName("font").length,b=0;b<c;b++)l=GetNodeValueIdx(k,"font",b),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","font_family"),a.setAttribute("name",
"font_family[]"),a.setAttribute("value",l),f.appendChild(a);if("8"==g){e=GetNode(h,"setting");b=GetNodeValue(e,"grid_color");a=document.createElement("input");a.setAttribute("type","hidden");a.setAttribute("id","grid_color");a.setAttribute("name","grid_color");a.setAttribute("value",b);f.appendChild(a);c=GetNodeValue(e,"grid_color_nm");a=document.createElement("input");a.setAttribute("type","hidden");a.setAttribute("id","grid_color_nm");a.setAttribute("name","grid_color_nm");a.setAttribute("value",
c);f.appendChild(a);""==b?(document.getElementById("grid_color_value").style.backgroundColor="#8b0000",document.getElementById("grid_color_text").innerHTML="Dark Red"):(document.getElementById("grid_color_value").style.backgroundColor=b,document.getElementById("grid_color_text").innerHTML=c);a=document.createElement("ul");for(b=0;b<dext5_admin_lang.grid_color_value.length;b++){var m=dext5_admin_lang.grid_color_value[b];c=dext5_admin_lang.grid_color_text[b];k=document.createElement("li");k.onclick=
function(a,b){return function(){document.getElementById("grid_color_value").style.backgroundColor=a;document.getElementById("grid_color_text").innerHTML=b;document.getElementById("grid_color").value=a;document.getElementById("grid_color_nm").value=b;document.getElementById("grid_color_flag").value="N";document.getElementById("grid_color_list").style.display="none"}}(m,c);l=document.createElement("a");l.className="sebt";l.title=c;var n=document.createElement("span");n.className="cr";n.style.backgroundColor=
m;m=document.createElement("span");m.className="crn";m.innerHTML=c;l.appendChild(n);l.appendChild(m);k.appendChild(l);a.appendChild(k)}document.getElementById("grid_color_list").appendChild(a);c=GetNodeValue(e,"grid_spans");for(b=0;b<dext5_admin_lang.grid_spans.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.grid_spans[b]),a.innerHTML=dext5_admin_lang.grid_spans[b],document.getElementById("grid_spans").appendChild(a),dext5_admin_lang.grid_spans[b]==c&&(a.selected=
!0);c=GetNodeValue(e,"grid_form");a=document.createElement("input");a.setAttribute("type","hidden");a.setAttribute("id","grid_form");a.setAttribute("name","grid_form");a.setAttribute("value",c);f.appendChild(a);for(b=0;b<document.getElementsByName("grid_form_radio").length;b++)document.getElementsByName("grid_form_radio")[b].value==c&&(document.getElementsByName("grid_form_radio")[b].checked=!0);c=GetNodeValue(e,"encoding");for(b=0;b<dext5_admin_lang.encoding_value.length;b++)a=document.createElement("option"),
a.setAttribute("value",dext5_admin_lang.encoding_value[b]),a.innerHTML=dext5_admin_lang.encoding_text[b],document.getElementById("encoding").appendChild(a),dext5_admin_lang.encoding_value[b]==c&&(a.selected=!0);c=GetNodeValue(e,"doctype");for(b=0;b<dext5_admin_lang.doctype_value.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.doctype_value[b]),a.innerHTML=dext5_admin_lang.doctype_text[b],document.getElementById("doctype").appendChild(a),dext5_admin_lang.doctype_value[b]==
c&&(a.selected=!0);b=GetNodeValue(e,"xmlnsname");a=document.createElement("input");a.setAttribute("type","hidden");a.setAttribute("id","xmlnsname");a.setAttribute("name","xmlnsname");a.setAttribute("value",b);f.appendChild(a);c=GetNodeValue(e,"doc_lang");for(b=0;b<dext5_admin_lang.doc_lang.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.doc_lang[b]),a.innerHTML=dext5_admin_lang.doc_lang[b],document.getElementById("doc_lang").appendChild(a),dext5_admin_lang.doc_lang[b]==
c&&(a.selected=!0);c=GetNodeValue(e,"lang");for(b=0;b<document.getElementById("lang").length;b++)document.getElementById("lang").options[b].value==c&&(document.getElementById("lang").options[b].selected=!0);b=GetNodeValue(e,"width");document.getElementById("width").value=b.substring(0,b.length-2);b=GetNodeValue(e,"height");document.getElementById("height").value=b.substring(0,b.length-2);c=GetNodeValue(e,"skinname");a=document.createElement("input");a.setAttribute("type","hidden");a.setAttribute("id",
"skinname");a.setAttribute("name","skinname");""==c?a.setAttribute("value","blue"):a.setAttribute("value",c);f.appendChild(a);a=0;if(""!=c)for(b=0;b<dext5_admin_lang.skinname_value.length;b++)dext5_admin_lang.skinname_text[b].toLowerCase()==c&&(a=b);document.getElementById("skinname_value").style.backgroundColor=dext5_admin_lang.skinname_value[a];document.getElementById("skinname_text").innerHTML=dext5_admin_lang.skinname_text[a];a=document.createElement("ul");for(b=0;b<dext5_admin_lang.skinname_value.length;b++)m=
dext5_admin_lang.skinname_value[b],c=dext5_admin_lang.skinname_text[b],k=document.createElement("li"),k.onclick=function(a,b){return function(){document.getElementById("skinname_value").style.backgroundColor=a;document.getElementById("skinname_text").innerHTML=b;document.getElementById("skinname").value=b.toLowerCase();document.getElementById("skinname_flag").value="N";document.getElementById("skinname_list").style.display="none"}}(m,c),l=document.createElement("a"),l.className="sebt",l.title=c,n=
document.createElement("span"),n.className="cr",n.style.backgroundColor=m,m=document.createElement("span"),m.className="crn",m.innerHTML=c,l.appendChild(n),l.appendChild(m),k.appendChild(l),a.appendChild(k);document.getElementById("skinname_list").appendChild(a);k=GetNodeValue(e,"font_family");n=GetNode(h,"font_family");c=n.getElementsByTagName("font").length;for(b=0;b<c;b++)l=GetNodeValueIdx(n,"font",b),a=document.createElement("option"),a.setAttribute("value",l),a.innerHTML=l,document.getElementById("setting_font_family").appendChild(a),
l==k&&(a.selected=!0);k=GetNodeValue(e,"font_size");n=GetNode(h,"font_size");c=n.getElementsByTagName("size").length;for(b=0;b<c;b++)l=GetNodeValueIdx(n,"size",b),a=document.createElement("option"),a.setAttribute("value",l),a.innerHTML=l,document.getElementById("setting_font_size").appendChild(a),l==k&&(a.selected=!0);c=GetNodeValue(e,"accessibility");for(b=0;b<dext5_admin_lang.accessibility_value.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.accessibility_value[b]),
a.innerHTML=dext5_admin_lang.accessibility_text[b],document.getElementById("accessibility").appendChild(a),dext5_admin_lang.accessibility_value[b]==c&&(a.selected=!0);c=GetNodeValue(e,"topmenu");for(b=0;b<dext5_admin_lang.topmenu_value.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.topmenu_value[b]),a.innerHTML=dext5_admin_lang.topmenu_text[b],document.getElementById("topmenu").appendChild(a),dext5_admin_lang.topmenu_value[b]==c&&(a.selected=!0);c=GetNodeValue(e,
"toolbar");for(b=0;b<dext5_admin_lang.toolbar_value.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.toolbar_value[b]),a.innerHTML=dext5_admin_lang.toolbar_text[b],document.getElementById("toolbar").appendChild(a),dext5_admin_lang.toolbar_value[b]==c&&(a.selected=!0);c=GetNodeValue(e,"statusbar");for(b=0;b<dext5_admin_lang.statusbar_value.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.statusbar_value[b]),a.innerHTML=dext5_admin_lang.statusbar_text[b],
document.getElementById("statusbar").appendChild(a),dext5_admin_lang.statusbar_value[b]==c&&(a.selected=!0);e=GetNodeValue(e,"showdialog_pos");for(b=0;b<dext5_admin_lang.showdialog_pos_value.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.showdialog_pos_value[b]),a.innerHTML=dext5_admin_lang.showdialog_pos_text[b],document.getElementById("showdialog_pos").appendChild(a),dext5_admin_lang.showdialog_pos_value[b]==e&&(a.selected=!0)}else e=GetNode(h,"setting"),b=
GetNodeValue(e,"grid_color"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","grid_color"),a.setAttribute("name","grid_color"),a.setAttribute("value",b),f.appendChild(a),c=GetNodeValue(e,"grid_color_nm"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","grid_color_nm"),a.setAttribute("name","grid_color_nm"),a.setAttribute("value",c),f.appendChild(a),c=GetNodeValue(e,"grid_spans"),a=document.createElement("input"),a.setAttribute("type",
"hidden"),a.setAttribute("id","grid_spans"),a.setAttribute("name","grid_spans"),a.setAttribute("value",c),f.appendChild(a),c=GetNodeValue(e,"grid_form"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","grid_form"),a.setAttribute("name","grid_form"),a.setAttribute("value",c),f.appendChild(a),c=GetNodeValue(e,"encoding"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","encoding"),a.setAttribute("name","encoding"),a.setAttribute("value",
c),f.appendChild(a),c=GetNodeValue(e,"doctype"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","doctype"),a.setAttribute("name","doctype"),a.setAttribute("value",c),f.appendChild(a),b=GetNodeValue(e,"xmlnsname"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","xmlnsname"),a.setAttribute("name","xmlnsname"),a.setAttribute("value",b),f.appendChild(a),c=GetNodeValue(e,"doc_lang"),a=document.createElement("input"),a.setAttribute("type",
"hidden"),a.setAttribute("id","doc_lang"),a.setAttribute("name","doc_lang"),a.setAttribute("value",c),f.appendChild(a),c=GetNodeValue(e,"lang"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","lang"),a.setAttribute("name","lang"),a.setAttribute("value",c),f.appendChild(a),b=GetNodeValue(e,"width"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","width"),a.setAttribute("name","width"),a.setAttribute("value",b),f.appendChild(a),
b=GetNodeValue(e,"height"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","height"),a.setAttribute("name","height"),a.setAttribute("value",b),f.appendChild(a),c=GetNodeValue(e,"skinname"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","skinname"),a.setAttribute("name","skinname"),a.setAttribute("value",c),f.appendChild(a),k=GetNodeValue(e,"font_family"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id",
"setting_font_family"),a.setAttribute("name","setting_font_family"),a.setAttribute("value",k),f.appendChild(a),k=GetNodeValue(e,"font_size"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","setting_font_size"),a.setAttribute("name","setting_font_size"),a.setAttribute("value",k),f.appendChild(a),c=GetNodeValue(e,"accessibility"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","accessibility"),a.setAttribute("name","accessibility"),
a.setAttribute("value",c),f.appendChild(a),c=GetNodeValue(e,"topmenu"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","topmenu"),a.setAttribute("name","topmenu"),a.setAttribute("value",c),f.appendChild(a),"2"==g&&("0"==c?document.getElementById("topmenu_none").checked=!1:"1"==c&&(document.getElementById("topmenu_none").checked=!0,document.getElementById("all_menu").disabled=!0,document.getElementById("set_menu").disabled=!0,document.getElementById("all_right").style.display=
"none",document.getElementById("right").style.display="none",document.getElementById("all_left").style.display="none",document.getElementById("left").style.display="none",document.getElementById("top").style.display="none",document.getElementById("bottom").style.display="none",f.appendChild(a))),c=GetNodeValue(e,"toolbar"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","toolbar"),a.setAttribute("name","toolbar"),a.setAttribute("value",c),f.appendChild(a),"3"==
g&&("0"==c?(document.getElementById("toolbar1_none").checked=!1,document.getElementById("toolbar2_none").checked=!1):"1"==c?(document.getElementById("toolbar1_none").checked=!0,document.getElementById("toolbar2_none").checked=!1,document.getElementById("set_menu1").disabled=!0,document.getElementById("all_right1").style.display="none",document.getElementById("right1").style.display="none",document.getElementById("all_left1").style.display="none",document.getElementById("left1").style.display="none",
document.getElementById("top1").style.display="none",document.getElementById("bottom1").style.display="none"):"2"==c?(document.getElementById("toolbar1_none").checked=!1,document.getElementById("toolbar2_none").checked=!0,document.getElementById("set_menu2").disabled=!0,document.getElementById("all_right2").style.display="none",document.getElementById("right2").style.display="none",document.getElementById("all_left2").style.display="none",document.getElementById("left2").style.display="none",document.getElementById("top2").style.display=
"none",document.getElementById("bottom2").style.display="none"):"3"==c&&(document.getElementById("toolbar1_none").checked=!0,document.getElementById("toolbar2_none").checked=!0,document.getElementById("all_menu").disabled=!0,document.getElementById("set_menu1").disabled=!0,document.getElementById("all_right1").style.display="none",document.getElementById("right1").style.display="none",document.getElementById("all_left1").style.display="none",document.getElementById("left1").style.display="none",document.getElementById("top1").style.display=
"none",document.getElementById("bottom1").style.display="none",document.getElementById("set_menu2").disabled=!0,document.getElementById("all_right2").style.display="none",document.getElementById("right2").style.display="none",document.getElementById("all_left2").style.display="none",document.getElementById("left2").style.display="none",document.getElementById("top2").style.display="none",document.getElementById("bottom2").style.display="none")),c=GetNodeValue(e,"statusbar"),a=document.createElement("input"),
a.setAttribute("type","hidden"),a.setAttribute("id","statusbar"),a.setAttribute("name","statusbar"),a.setAttribute("value",c),f.appendChild(a),"4"==g&&("0"==c?document.getElementById("statusbar_none").checked=!1:"1"==c&&(document.getElementById("statusbar_none").checked=!0,document.getElementById("all_menu").disabled=!0,document.getElementById("set_menu").disabled=!0,document.getElementById("all_right").style.display="none",document.getElementById("right").style.display="none",document.getElementById("all_left").style.display=
"none",document.getElementById("left").style.display="none",document.getElementById("top").style.display="none",document.getElementById("bottom").style.display="none",f.appendChild(a))),e=GetNodeValue(e,"showdialog_pos"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","showdialog_pos"),a.setAttribute("name","showdialog_pos"),a.setAttribute("value",e),f.appendChild(a);if("9"==g){h=GetNode(h,"uploader_setting");e=GetNodeValue(h,"develop_langage");for(b=0;b<dext5_admin_lang.develop_langage.length;b++)a=
document.createElement("option"),a.setAttribute("value",dext5_admin_lang.develop_langage[b]),a.innerHTML=dext5_admin_lang.develop_langage[b],document.getElementById("develop_langage").appendChild(a),dext5_admin_lang.develop_langage[b]==e&&(a.selected=!0);b=GetNodeValue(h,"handler_url");""==b?(document.getElementById("chk_handler_url").checked="checked",document.getElementById("handler_url").disabled="disabled",document.getElementById("span_desc").innerHTML=dext5_admin_lang.upload_url_desc1):(document.getElementById("chk_handler_url").checked=
!1,document.getElementById("handler_url").disabled=!1,document.getElementById("span_desc").innerHTML=dext5_admin_lang.upload_url_desc2);document.getElementById("handler_url").value=b;b=GetNodeValue(h,"to_save_path_url");""==b?(document.getElementById("chk_to_save_path_url").checked="checked",document.getElementById("to_save_path_url").disabled="disabled",document.getElementById("span_desc2").innerHTML=dext5_admin_lang.save_path_desc1):(document.getElementById("chk_to_save_path_url").checked=!1,document.getElementById("to_save_path_url").disabled=
!1,document.getElementById("span_desc2").innerHTML=dext5_admin_lang.save_path_desc2);document.getElementById("to_save_path_url").value=b;e=GetNodeValue(h,"save_foldername_rule");for(b=0;b<dext5_admin_lang.save_foldername_rule.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.save_foldername_rule[b]),a.innerHTML=""==dext5_admin_lang.save_foldername_rule[b]?"None":dext5_admin_lang.save_foldername_rule[b],document.getElementById("save_foldername_rule").appendChild(a),
dext5_admin_lang.save_foldername_rule[b]==e&&(a.selected=!0);e=GetNodeValue(h,"save_filename_rule");for(b=0;b<dext5_admin_lang.save_filename_rule.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.save_filename_rule[b]),a.innerHTML=""==dext5_admin_lang.save_filename_rule[b]?"None":dext5_admin_lang.save_filename_rule[b],document.getElementById("save_filename_rule").appendChild(a),dext5_admin_lang.save_filename_rule[b]==e&&(a.selected=!0);e=GetNodeValue(h,"image_convert_format");
for(b=0;b<dext5_admin_lang.image_convert_format.length;b++)a=document.createElement("option"),a.setAttribute("value",dext5_admin_lang.image_convert_format[b]),a.innerHTML=""==dext5_admin_lang.image_convert_format[b]?"None":dext5_admin_lang.image_convert_format[b],document.getElementById("image_convert_format").appendChild(a),dext5_admin_lang.image_convert_format[b]==e&&(a.selected=!0);b=GetNodeValue(h,"image_convert_width");document.getElementById("image_convert_width").value=b;h=GetNodeValue(h,"image_convert_height");
document.getElementById("image_convert_height").value=h}else h=GetNode(h,"uploader_setting"),e=GetNodeValue(h,"develop_langage"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","develop_langage"),a.setAttribute("name","develop_langage"),a.setAttribute("value",e),f.appendChild(a),b=GetNodeValue(h,"handler_url"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","handler_url"),a.setAttribute("name","handler_url"),a.setAttribute("value",
b),f.appendChild(a),b=GetNodeValue(h,"to_save_path_url"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","to_save_path_url"),a.setAttribute("name","to_save_path_url"),a.setAttribute("value",b),f.appendChild(a),e=GetNodeValue(h,"save_foldername_rule"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","save_foldername_rule"),a.setAttribute("name","save_foldername_rule"),a.setAttribute("value",e),f.appendChild(a),e=GetNodeValue(h,
"save_filename_rule"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","save_filename_rule"),a.setAttribute("name","save_filename_rule"),a.setAttribute("value",e),f.appendChild(a),e=GetNodeValue(h,"image_convert_format"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","image_convert_format"),a.setAttribute("name","image_convert_format"),a.setAttribute("value",e),f.appendChild(a),b=GetNodeValue(h,"image_convert_width"),a=document.createElement("input"),
a.setAttribute("type","hidden"),a.setAttribute("id","image_convert_width"),a.setAttribute("name","image_convert_width"),a.setAttribute("value",b),f.appendChild(a),h=GetNodeValue(h,"image_convert_height"),a=document.createElement("input"),a.setAttribute("type","hidden"),a.setAttribute("id","image_convert_height"),a.setAttribute("name","image_convert_height"),a.setAttribute("value",h),f.appendChild(a)}
function move_all_option(d,g,f){for(var a=[],c=0;c<d.length;c++){if("design"!=d.options[c].value){a.push(d.options[c]);var h=document.createElement("option");h.value=d.options[c].value;h.innerHTML=d.options[c].innerHTML;g.appendChild(h)}if(c==d.length-1)for(h=0;h<a.length;h++)a[h].value!=f&&d.removeChild(a[h])}}
function move_option(d,g,f){for(var a=[],c=0;c<d.length;c++){if(!0==d.options[c].selected){var h=document.createElement("option");h.value=d.options[c].value;h.innerHTML=d.options[c].innerHTML;g.appendChild(h);a.push(d.options[c])}if(c==d.length-1)for(h=0;h<a.length;h++)a[h].value!=f&&d.removeChild(a[h])}}
function upExcute(d){for(var g=d.length,f=[],a=0;a<g;a++)if(!0==d.options[a].selected&&(f.push(d.options[a]),0<=a-1&&f[0]!=d.options[0])){var c=d.options[a-1].value,h=d.options[a-1].innerHTML;d.options[a-1].value=d.options[a].value;d.options[a-1].innerHTML=d.options[a].innerHTML;d.options[a].value=c;d.options[a].innerHTML=h;d.options[a-1].selected=!0;d.options[a].selected=!1}}
function bottomExcute(d){for(var g=d.length,f=[],a=g-1;0<=a;a--)!0==d.options[a].selected&&f.push(d.options[a]);for(a=g-1;0<=a&&f[0]!=d.options[g-1];a--)if(!0==d.options[a].selected&&a+1<=g-1){var c=d.options[a+1].value,h=d.options[a+1].innerHTML;d.options[a+1].value=d.options[a].value;d.options[a+1].innerHTML=d.options[a].innerHTML;d.options[a].value=c;d.options[a].innerHTML=h;d.options[a+1].selected=!0;d.options[a].selected=!1}}
function setCookieSave(d,g,f){var a=new Date;a.setDate(a.getDate()+f);document.cookie=d+"="+escape(g)+"; path=/; expires="+a.toGMTString()+";"}function getLoginCookei(){var d=document.cookie+";",g=d.indexOf("id",0),f="";-1!=g&&(d=d.substring(g,d.length),begin=d.indexOf("=",0)+1,end=d.indexOf(";",begin),f=unescape(d.substring(begin,end)));""!=f&&(document.getElementById("id").value=f,document.getElementById("id_check").checked=!0)}
var Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(d){var g="",f,a,c,h,e,b,k=0;for(d=Base64._utf8_encode(d);k<d.length;)f=d.charCodeAt(k++),a=d.charCodeAt(k++),c=d.charCodeAt(k++),h=f>>2,f=(f&3)<<4|a>>4,e=(a&15)<<2|c>>6,b=c&63,isNaN(a)?e=b=64:isNaN(c)&&(b=64),g=g+this._keyStr.charAt(h)+this._keyStr.charAt(f)+this._keyStr.charAt(e)+this._keyStr.charAt(b);return g},decode:function(d){var g="",f,a,c,h,e,b=0;for(d=d.replace(/[^A-Za-z0-9\+\/\=]/g,"");b<
d.length;)f=this._keyStr.indexOf(d.charAt(b++)),a=this._keyStr.indexOf(d.charAt(b++)),h=this._keyStr.indexOf(d.charAt(b++)),e=this._keyStr.indexOf(d.charAt(b++)),f=f<<2|a>>4,a=(a&15)<<4|h>>2,c=(h&3)<<6|e,g+=String.fromCharCode(f),64!=h&&(g+=String.fromCharCode(a)),64!=e&&(g+=String.fromCharCode(c));return g=Base64._utf8_decode(g)},_utf8_encode:function(d){d=d.replace(/\r\n/g,"\n");for(var g="",f=0;f<d.length;f++){var a=d.charCodeAt(f);128>a?g+=String.fromCharCode(a):(127<a&&2048>a?g+=String.fromCharCode(a>>
6|192):(g+=String.fromCharCode(a>>12|224),g+=String.fromCharCode(a>>6&63|128)),g+=String.fromCharCode(a&63|128))}return g},_utf8_decode:function(d){for(var g="",f=0,a=c1=c2=0;f<d.length;)a=d.charCodeAt(f),128>a?(g+=String.fromCharCode(a),f++):191<a&&224>a?(c2=d.charCodeAt(f+1),g+=String.fromCharCode((a&31)<<6|c2&63),f+=2):(c2=d.charCodeAt(f+1),c3=d.charCodeAt(f+2),g+=String.fromCharCode((a&15)<<12|(c2&63)<<6|c3&63),f+=3);return g},URLEncode:function(d){return escape(this._utf8_encode(d))},URLDecode:function(d){return this._utf8_decode(unescape(d))}};
